FROM heroiclabs/nakama:3.20.0

COPY local.yml /nakama/data/local.yml
COPY modules /nakama/data/modules
COPY render/start.sh /nakama/data/start.sh

RUN chmod +x /nakama/data/start.sh

ENTRYPOINT ["/nakama/data/start.sh"]
