name: "lumarush-nakama"
logger:
  level: "INFO"

session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 604800

socket:
  server_key: "lumarush-dev-key"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "adminpassword"

runtime:
  path: "/nakama/data/modules"
  js_entrypoint: "lumarush.js"
  env:
    - "TPX_PLATFORM_AUTH_URL="
    - "TPX_PLATFORM_EVENT_URL="
    - "TPX_PLATFORM_API_KEY="
    - "TPX_PLATFORM_IDENTITY_NAKAMA_AUTH_URL=http://host.docker.internal:8080/v1/auth/nakama"
    - "TPX_PLATFORM_IAP_VERIFY_URL=http://host.docker.internal:8110/v1/iap/verify"
    - "TPX_PLATFORM_IAP_ENTITLEMENTS_URL=http://host.docker.internal:8110/v1/iap/entitlements"
    - "TPX_PLATFORM_IAP_COINS_ADJUST_URL=http://host.docker.internal:8110/v1/iap/coins/adjust"
    - "TPX_HTTP_TIMEOUT_MS=5000"
    - "LUMARUSH_LEADERBOARD_ID=lumarush_high_scores"
